### PR TITLE
Production gems

### PR DESCRIPTION
**Pull request by yuric**
production gems?

### CODE REVIEW

**Comment by WebEpic** [comment]
did that here - https://github.com/WebEpic/roddit/tree/heroku_ready - wouldn't deploy on Heroku until I did. Just didn't merge with master yet.

**Comment by yuric** [comment]
gotcha. Did it require the heroku gem to be in production as well?

**Comment by yuric** [comment]
I just removed it from the dev group which is only installed locally as you probably already know =)

**Comment by WebEpic** [comment]
Yes I knew that the dev group was only installed locally, or rather I figured it out after my app kept failing to deploy + reading the logs. 

No, the heroku gem wasn't required. 

Just saw these comments btw.

**Pull request closed without merging**
